---
- name: Configure cart
  hosts: cart
  become: true 
  tasks:
   - name: Enable nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: Install nodejs
     ansible.builtin.dnf:
      name: nodejs
      state: present
   
   - name: Create roboshop user
     ansible.builtin.user:
       name: roboshop
       comment: "roboshop system user"
       system: true
       home: /app
       shell: /sbin/nologin

   - name: Delete app Directory
     ansible.builtin.file:
       name: /app 
       state: absent
   
   - name: Create app Directory
     ansible.builtin.file:
       name: /app
       state: directory

   - name: Delete app code in tmp Directory 
     ansible.builtin.file: 
      name: /tmp/cart.zip
      state: absent 

   - name: download application code
     ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
       dest: /tmp/cart.zip

   - name: unarchive cart zip file
     ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

   - name: Install npm
     community.general.npm:
      path: /app
      state: latest
  
   - name: copy cart service to /etc/systemd/system/cart.service
     ansible.builtin.template:
      src: cart.service.j2
      dest: /etc/systemd/system/cart.service

   - name: systemd reload
     ansible.builtin.systemd_service:
       daemon_reload: true
  
  
   - name: Enable and Start cart Service
     ansible.builtin.service:
       name: cart
       state: restarted
       enabled: true