[local]
localhost

[mongodb]
mongodb-dev.daws88s.shop

[mysql]
mysql-dev.daws88s.shop 

[redis]
redis-dev.daws88s.shop

[rabbitmq]
rabbitmq-dev.daws88s.shop

[catalogue]
catalogue-dev.daws88s.shop

[frontend]
frontend-dev.daws88s.shop