---
 - name: Install mysql server 
   hosts: mysql 
   become: true 
   tasks:
     - name: Install mysql
       ansible.builtin.dnf:
         name: mysql-server
         state: present 

     - name: Enable and Start the Service 
       ansible.builtin.service: 
          name: mysqld 
          enabled: yes 
          state: started 

          