---
- name: Configure Shipping
  hosts: shipping 
  become: true 
  vars:
     sql_hostname: mysql-dev.daws88s.shop
     mysql_user: root
     mysql_password: RoboShop@1
  tasks: 
    - name: Install maven 
      ansible.builtin.dnf:
        name: maven 
        state: present
    
    - name: Create roboshop user
      ansible.builtin.user:
        name: roboshop
        comment: "roboshop system user"
        system: true
        home: /app
        shell: /sbin/nologin 
    
    - name: Delete app Directory
      ansible.builtin.file:
       name: /app 
       state: absent

    - name: Create app Directory
      ansible.builtin.file:
        name: /app
        state: directory
    
    - name: Delete app code in tmp Directory 
      ansible.builtin.file: 
       name: /tmp/shipping.zip
       state: absent 

    - name: download application code
      ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
       dest: /tmp/shipping.zip
    
    - name: unarchive shipping.jar zip file
      ansible.builtin.unarchive:
        src: /tmp/shipping.zip
        dest: /app
        remote_src: yes

    - name: change dir to /app and run mvn clean package
      ansible.builtin.command:  mvn clean package 
      args:
         chdir: /app

    - name: copy file from target/shipping-1.0.jar shipping.jar 
      ansible.builtin.copy:
        src: /app/target/shipping-1.0.jar
        dest: /app/shipping.jar
        remote_src: yes
    
    - name: copy shipping service to /etc/systemd/system/shipping.service
      ansible.builtin.copy:
       src: shipping.service.j2 
       dest: /etc/systemd/system/shipping.service
       

    - name: systemd reload
      ansible.builtin.systemd_service:
       daemon_reload: true
       
    - name: Install mysql 
      ansible.builtin.dnf: 
        name: mysql 
        state: present

    - name: Install dependencies for mysql
      ansible.builtin.pip:
        name: "{{ item }}"
      loop: 
      - PyMySQL

    - name: Enable and Start Shipping Service
      ansible.builtin.service:
       name: shipping
       state: started
       enabled: true

    - name: Create target database if it does not exist
      community.mysql.mysql_db:
         name: all
         login_host: "{{ sql_hostname }}"
         login_user: "{{ mysql_user }}"
         login_password: "{{ mysql_password }}"
         state: import 
         target: "{{ item }}"
      loop:
            - /app/db/schema.sql
            - /app/db/app-user.sql 
            - /app/db/master-data.sql