---
- name: Configure user
  hosts: user
  become: true 
  tasks:
   - name: Enable nodejs
     ansible.builtin.command: dnf module enable nodejs:20 -y

   - name: Install nodejs
     ansible.builtin.dnf:
      name: nodejs
      state: present
   
   - name: Create roboshop user
     ansible.builtin.user:
       name: roboshop
       comment: "roboshop system user"
       system: true
       home: /app
       shell: /sbin/nologin

   - name: Delete app Directory
     ansible.builtin.file:
       name: /app 
       state: absent
   
   - name: Create app Directory
     ansible.builtin.file:
       name: /app
       state: directory
  
   - name: Delete app code in tmp Directory 
     ansible.builtin.file: 
      name: /tmp/user.zip
      state: absent 

   - name: download application code
     ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip 
       dest: /tmp/user.zip

   - name: unarchive user zip file
     ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

   - name: Install npm
     community.general.npm:
      path: /app
      state: latest
  
   - name: copy user service 
     ansible.builtin.template:
      src: user.service.j2
      dest: /etc/systemd/system/user.service

   - name: systemd reload
     ansible.builtin.systemd_service:
       daemon_reload: true
       name: user
  
   - name: Enable and Start user Service
     ansible.builtin.service:
       name: user
       state: started
       enabled: true